NUM_COLS = 50
NUM_ROWS = 25

SQUARE_SIDE = 25

# 625 * 1250
WINDOW_HEIGHT = NUM_ROWS * SQUARE_SIDE
WINDOW_WIDTH = NUM_COLS * SQUARE_SIDE

GREEN_COLOR = (0, 128, 0)
BLACK_COLOR = (0, 0, 0)

GRASS_AMOUNT = 20
GRASS_HEIGHT = 50
GRASS_WIDTH = 50

MINE_AMOUNT = 20
MINE_HEIGHT = 1 * SQUARE_SIDE
MINE_WIDTH = 3 * SQUARE_SIDE

FLAG_START_ROW = 21
FLAG_END_ROW = 23
FLAG_START_COL = 46
FLAG_END_COL = 49

RIGHT = 'right'
LEFT = 'left'
UP = 'up'
DOWN = 'down'

SOLDIER = 'soldier'
EMPTY = 'empty'
GRASS = 'grass'
MINE = 'mine'
RIGHT_LEG = 'legs'
START_POSITION = 0

GRASS_IMG = "grass.png"
SOLDIER_IMG = "soldier1.png"
MINE_IMG = "mine.png"
FLAG_IMG = 'flag.png'

SOLDIER_HEIGHT = 4 * SQUARE_SIDE
SOLDIER_WIDTH = 4 * SQUARE_SIDE

FLAG_HEIGHT = 3 * SQUARE_SIDE
FLAG_WIDTH = 4 * SQUARE_SIDE

