NUM_COLS = 50
NUM_ROWS = 25

SQUARE_SIDE = 20

WINDOW_HEIGHT = NUM_ROWS * SQUARE_SIDE
WINDOW_WIDTH = NUM_COLS * SQUARE_SIDE

GREEN_COLOR = (0, 128, 0)
BLACK_COLOR = (0, 0, 0)
GRASS_IMG = "grass.png"
GRASS_AMOUNT = 20
GRASS_HEIGHT = 50
GRASS_WIDTH = 50

MINE_AMOUNT = 20
MINE_HEIGHT = 1
MINE_WIDTH = 3

FLAG_START_ROW = 21
FLAG_END_ROW = 23
FLAG_START_COL = 46
FLAG_END_COL = 49

RIGHT = 'right'
LEFT = 'left'
UP = 'up'
DOWN = 'down'

SOLDIER = 'soldier'
EMPTY = 'empty'
START_POSITION = 0
